# Generated by Django 5.2.1 on 2025-06-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('message_reason', models.CharField(choices=[('Account', 'Account Issues'), ('Business', 'Business Inquiry'), ('Moderation', 'Issues with another user'), ('Event Organisation', 'Event organisation issues'), ('Tickets', 'Booking / Ticket issues'), ('Other', 'Not Specified / Other')], default='Other')),
                ('content', models.TextField(max_length=2000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('message_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
