# Generated by Django 5.2.1 on 2025-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_message_guest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='guest_email',
            field=models.EmailField(max_length=254),
        ),
    ]
