# Generated by Django 5.2.1 on 2025-06-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_message_guest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='guest_name',
            field=models.CharField(max_length=100),
        ),
    ]
